import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('electronAPI', {
  getQuestions: () => ipcRenderer.invoke('get-questions'),
  addQuestion: (data: any) => ipcRenderer.invoke('add-question', data),
  updateQuestion: (data: any) => ipcRenderer.invoke('update-question', data),
  deleteQuestion: (id: number) => ipcRenderer.invoke('delete-question', id),
  getSessions: () => ipcRenderer.invoke('get-sessions'),
  addSession: (data: any) => ipcRenderer.invoke('add-session', data),
  updateSession: (data: any) => ipcRenderer.invoke('update-session', data),
  deleteSession: (id: number) => ipcRenderer.invoke('delete-session', id),
  getSessionResults: () => ipcRenderer.invoke('get-sessionResults'),
  addSessionResult: (data: any) => ipcRenderer.invoke('add-sessionResult', data),
  getAdminSetting: (key: string) => ipcRenderer.invoke('get-adminSetting', key),
  setAdminSetting: (data: { key: string; value: any }) => ipcRenderer.invoke('set-adminSetting', data),
  getVotingDevices: () => ipcRenderer.invoke('get-votingDevices'),
  addVotingDevice: (data: any) => ipcRenderer.invoke('add-votingDevice', data),
  getTrainers: () => ipcRenderer.invoke('get-trainers'),
  addTrainer: (data: any) => ipcRenderer.invoke('add-trainer', data),
  getSessionQuestions: (sessionId: number) => ipcRenderer.invoke('get-sessionQuestions', sessionId),
  addSessionQuestion: (data: any) => ipcRenderer.invoke('add-sessionQuestion', data),
  getSessionBoitiers: (sessionId: number) => ipcRenderer.invoke('get-sessionBoitiers', sessionId),
  addSessionBoitier: (data: any) => ipcRenderer.invoke('add-sessionBoitier', data),
  getReferentiels: () => ipcRenderer.invoke('get-referentiels'),
  addReferential: (data: any) => ipcRenderer.invoke('add-referential', data),
  getThemes: (referentielId: number) => ipcRenderer.invoke('get-themes', referentielId),
  addTheme: (data: any) => ipcRenderer.invoke('add-theme', data),
  getBlocs: (themeId: number) => ipcRenderer.invoke('get-blocs', themeId),
  addBloc: (data: any) => ipcRenderer.invoke('add-bloc', data),
  getDeviceKits: () => ipcRenderer.invoke('get-deviceKits'),
  addDeviceKit: (data: any) => ipcRenderer.invoke('add-deviceKit', data),
  getDeviceKitAssignments: (kitId: number) => ipcRenderer.invoke('get-deviceKitAssignments', kitId),
  addDeviceKitAssignment: (data: any) => ipcRenderer.invoke('add-deviceKitAssignment', data),
  exportDb: () => ipcRenderer.invoke('export-db'),
  importDb: (path: string) => ipcRenderer.invoke('import-db', path)
});